## Introduccion a Julia

#### Operaciones básicas

In [1]:
2 + 3 

5

In [2]:
5*3

15

In [3]:
2.6  * 6.3 

16.38

In [4]:
2.3/7

0.32857142857142857

In [7]:
3^5

243

In [8]:
2.6 ^ 5

118.81376000000002

In [9]:
exp(2)

7.38905609893065

In [10]:
exp(log(2))

2.0

In [11]:
log(2) # Acá ya usa la base natural

0.6931471805599453

In [14]:
log10(8) # Usamos la base 10

0.9030899869919435

In [16]:
log2(8) # Logaritmo de 8 en base 2

3.0

In [17]:
log10(2) + log10(5)

1.0

In [18]:
sin(0)

0.0

In [20]:
sin(pi) # va a dar casi 0 

1.2246467991473532e-16

In [21]:
sin(π)

1.2246467991473532e-16

In [23]:
# Usamos siempre radianes, si quiero usar en grados escribo
# donde el sind es seno en grados (degrees)
sind(90)

1.0

In [24]:
pi

π = 3.1415926535897...

In [25]:
π

π = 3.1415926535897...

Una de las cosas lindas que tiene julia es que podemos utilizar 
unicode para definir funciones, variables o lo que querramos

In [26]:
α = 1

1

In [29]:
β = 1 # \beta+tab

1

In [31]:
🐺 = 2 # tambien podemos usar emojis, posiblemente nos venga bien si queremos
# por ejemplo mostras algunas ecuacion diferencial como la del modelo presa depredador

2

In [36]:
mate = 2

2

In [37]:
mate * 3

6

In [38]:
"mate"

"mate"

In [42]:
"mate " * "cocido" # concanteamos (unimos)

"mate cocido"

#### Álgebra lineal

In [43]:
 v = [1.0;2.0;3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [44]:
v + v

3-element Vector{Float64}:
 2.0
 4.0
 6.0

In [45]:
v * 2 

3-element Vector{Float64}:
 2.0
 4.0
 6.0

In [47]:
w = [3.0;2.0;1.0]

3-element Vector{Float64}:
 3.0
 2.0
 1.0

In [48]:
v + w

3-element Vector{Float64}:
 4.0
 4.0
 4.0

In [49]:
2  * v + 3 * w

3-element Vector{Float64}:
 11.0
 10.0
  9.0

Distintas formas de definifir una matriz

In [51]:
A = [5.0  4.0  -2.0;
    1.0  2.0  5.0]

2×3 Matrix{Float64}:
 5.0  4.0  -2.0
 1.0  2.0   5.0

In [52]:
A = [5.0  4.0  -2.0;1.0  2.0  5.0]

2×3 Matrix{Float64}:
 5.0  4.0  -2.0
 1.0  2.0   5.0

In [53]:
A = [5.0  4.0  -2.0
    1.0  2.0  5.0]

2×3 Matrix{Float64}:
 5.0  4.0  -2.0
 1.0  2.0   5.0

In [54]:
# Multiplicacion matriz y vector

A * v

2-element Vector{Float64}:
  7.0
 20.0

In [55]:
A' # A transpuesta

3×2 adjoint(::Matrix{Float64}) with eltype Float64:
  5.0  1.0
  4.0  2.0
 -2.0  5.0

In [56]:
transpose(A)

3×2 transpose(::Matrix{Float64}) with eltype Float64:
  5.0  1.0
  4.0  2.0
 -2.0  5.0

In [58]:
adjoint(A)

3×2 adjoint(::Matrix{Float64}) with eltype Float64:
  5.0  1.0
  4.0  2.0
 -2.0  5.0

In [59]:
B = ones(2,3) # creamos una matriz de unos de 2 x 3

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [60]:
A + B

2×3 Matrix{Float64}:
 6.0  5.0  -1.0
 2.0  3.0   6.0

In [63]:
C = A + im*B

2×3 Matrix{ComplexF64}:
 5.0+1.0im  4.0+1.0im  -2.0+1.0im
 1.0+1.0im  2.0+1.0im   5.0+1.0im

In [65]:
transpose(C)

3×2 transpose(::Matrix{ComplexF64}) with eltype ComplexF64:
  5.0+1.0im  1.0+1.0im
  4.0+1.0im  2.0+1.0im
 -2.0+1.0im  5.0+1.0im

In [67]:
adjoint(C) # vemos que C' es la adjunta de C

3×2 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  5.0-1.0im  1.0-1.0im
  4.0-1.0im  2.0-1.0im
 -2.0-1.0im  5.0-1.0im

In [68]:
C'

3×2 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  5.0-1.0im  1.0-1.0im
  4.0-1.0im  2.0-1.0im
 -2.0-1.0im  5.0-1.0im

In [69]:
using LinearAlgebra

In [70]:
dot(v,w) # es producto interno

10.0

In [71]:
norm(v)

3.7416573867739413

In [73]:
A = [4.0  1.0
    2.0  3.0]

2×2 Matrix{Float64}:
 4.0  1.0
 2.0  3.0

In [74]:
b = [6.0;8.0]

2-element Vector{Float64}:
 6.0
 8.0

In [75]:
x = A \ b #busco la solucion

2-element Vector{Float64}:
 1.0
 2.0

In [77]:
A * x  - b 

2-element Vector{Float64}:
 0.0
 0.0

In [78]:
eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 2.0
 5.0
vectors:
2×2 Matrix{Float64}:
 -0.447214  0.707107
  0.894427  0.707107

In [79]:
λ , V = eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 2.0
 5.0
vectors:
2×2 Matrix{Float64}:
 -0.447214  0.707107
  0.894427  0.707107

In [80]:
λ

2-element Vector{Float64}:
 2.0
 5.0

In [81]:
V

2×2 Matrix{Float64}:
 -0.447214  0.707107
  0.894427  0.707107

In [82]:
lu(A)

LU{Float64, Matrix{Float64}}
L factor:
2×2 Matrix{Float64}:
 1.0  0.0
 0.5  1.0
U factor:
2×2 Matrix{Float64}:
 4.0  1.0
 0.0  2.5

In [83]:
qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}}
Q factor:
2×2 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}}:
 -0.894427  -0.447214
 -0.447214   0.894427
R factor:
2×2 Matrix{Float64}:
 -4.47214  -2.23607
  0.0       2.23607

In [84]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [85]:
zeros(4,5)

4×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [86]:
zeros(2,3,4)

2×3×4 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0
 0.0  0.0  0.0

In [87]:
rand(3,3)

3×3 Matrix{Float64}:
 0.0266026  0.312451    0.937416
 0.888416   0.575408    0.664259
 0.627643   0.00288413  0.0737161

In [88]:
rand(100)

100-element Vector{Float64}:
 0.45074329976697725
 0.6464287602273968
 0.32097467248571676
 0.07598484271683403
 0.6211228468040793
 0.0297060792300321
 0.2664869580011766
 0.8276124424822047
 0.3375523653649518
 0.6905982428598004
 ⋮
 0.5563440183122568
 0.9688114531327271
 0.7173245156136613
 0.16089817847789223
 0.686684742710546
 0.5396982126025069
 0.2950702516022705
 0.852592343497522
 0.16909158407434488

In [89]:
v

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [90]:
w

3-element Vector{Float64}:
 3.0
 2.0
 1.0

In [91]:
# Vamos a concatenar vectores
[v;w]

6-element Vector{Float64}:
 1.0
 2.0
 3.0
 3.0
 2.0
 1.0

In [93]:
[v  w] # Los coloco como columnas

3×2 Matrix{Float64}:
 1.0  3.0
 2.0  2.0
 3.0  1.0

In [94]:
v

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [95]:
V[1]

-0.4472135954999579

In [96]:
v[1]

1.0

In [97]:
A[2,2]

3.0

In [98]:
A

2×2 Matrix{Float64}:
 4.0  1.0
 2.0  3.0

In [99]:
:

(::Colon) (generic function with 15 methods)

In [102]:
A[:,2] # Quiero toda la columna 2

2-element Vector{Float64}:
 1.0
 3.0

In [104]:
A[:,1] # toda la columna 1

2-element Vector{Float64}:
 4.0
 2.0

In [105]:
A[1,:] # fila 1

2-element Vector{Float64}:
 4.0
 1.0

In [106]:
A[2,:] # fila 2

2-element Vector{Float64}:
 2.0
 3.0

In [107]:
B = rand(5,5)

5×5 Matrix{Float64}:
 0.88365   0.255608   0.153526   0.925579   0.0658387
 0.748229  0.398752   0.0673096  0.0394553  0.608074
 0.271252  0.0289899  0.0317758  0.151908   0.845485
 0.175995  0.452056   0.133272   0.304239   0.287591
 0.435663  0.682963   0.687147   0.685756   0.544643

In [108]:
B[2,2:4] # de la fila 2 quiero del elemento 2 al 4 inclusive

3-element Vector{Float64}:
 0.3987522379597872
 0.06730960622330695
 0.039455300093754975

In [109]:
B[2:5,2:4] # de la fila 2 a la 5 quiero del elemento 2 al 4 inclusive

4×3 Matrix{Float64}:
 0.398752   0.0673096  0.0394553
 0.0289899  0.0317758  0.151908
 0.452056   0.133272   0.304239
 0.682963   0.687147   0.685756